# Generated by Django 4.1.1 on 2022-09-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
